default_language_version:
  python: 'python3.10'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: no

      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        pass_filenames: no

      - id: test
        name: test
        entry: pytest
        language: system
        pass_filenames: no
